# fly.toml app configuration file generated for teledrive-sleebu on 2023-06-06T15:39:17+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "teledrive-sleebu"
primary_region = "cdg"
kill_signal = "SIGINT"
kill_timeout = "5s"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
